[[redirects]]
  from = "/"               # all requests to root
  to = "/netlify/functions/redirect"  # call the function
  status = 200             # 200 so function runs and decides redirect
  force = true   